# Generated by Django 2.1.1 on 2018-09-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataModel',
            new_name='Student',
        ),
    ]
